general:
  buildTool: "maven"
  buildDescriptor: "Helloworld/pom.xml"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false

steps:
  mavenExecute:
    goals: "clean package"

  cloudFoundryDeploy:
    cfManifest: "Helloworld/manifest.yml"